### PR TITLE
Added the ability for a cell to span multiple columns

### PR DESCRIPTION
**Pull request by damontallen**

### CODE REVIEW

**Comment by ianalis** [comment]
I'd only looked at the Column span test notebook but the test implementation that you have pointed at looks okay. Can you add a case in the test notebook where the column span of an existing cell is decreased? Can you convert the test cases into automated tests?

**Comment by damontallen** [comment]
@ianalis I added two col_span tests and an example of going from col_span=2 to 1.

**Comment by ianalis** [comment]
Out[11] seems to be a bit unintuitive. I was expecting that the rest of the columns would shift left so that there is a missing cell in the rightmost column. However, if we think of reducing col_span as equivalent to splitting a cell then the output feels correct.

The automated tests can be moved inside tests/test_basic.py or placed in a separate file in tests.

There are also conflicts so you will have to resolve those before I can pull.

**Comment by damontallen** [comment]
The tests are in test_basic.py already.  Where would I find the conflicts?
Are you referring to my paster branch?

**Comment by ianalis** [comment]
The branch in this PR, which is `col_span`.

**Comment by damontallen** [comment]
OK... How can I resolve those conflicts If I don't have access to the
original repository?  If this is a stupid question, bare in mind that this
is the most complicated contribution I've done to a repository that is not
my own and I'm not really that experienced with git.

**Comment by ianalis** [comment]
Try the following in your `col_span` branch:

    git pull -u https://github.com/takluyver/tabipy

This will result to a merge conflict which you should then resolve by editing the conflicted files. Commit and push all changes and, if everything works as expected, I will be able to merge your PR.

**Comment by damontallen** [comment]
Thanks for the instructions.  I have resolved the conflicts.

**Comment by damontallen** [comment]
@ianalis I don't understand the Travis CI build failed otherwise I'd fix it now.  I'm a little busy with another project, so if you wait on me to make the change it may be a few days.

**Comment by ianalis** [comment]
If you look at the [build log](https://travis-ci.org/takluyver/tabipy/builds/47318463), there is a syntax error at

    def  __init__(self, *cells, max_len=None):

Python 2.7 does not allow keyword arguments after arbitrary argument lists in the function prototype. The solution is to do something like

    def  __init__(self, *cells, **opts):

and access the argument with

    opts.get('max_len')

**Pull request merged**
